### ISSUE TITLE
Please deactivate OpenGL/Acceleration usage for the webkit/browser part 

### ISSUE THREAD

**Issue by Tids** [flathub/com.github.johnfactotum.Foliate#1]
https://gitlab.gnome.org/GNOME/epiphany/issues/551
https://gitlab.gnome.org/GNOME/gtk/issues/1401
https://bugs.webkit.org/show_bug.cgi?id=192522

Issue is explained in there, Upstream gnome already have disabled OpenGL in Gnome Web, would be nice if you could also do that until its fixed/the fix is released.

Not sure if this is even your part, tbh. Maybe its more of a freedesktop runtime/gnome runtime thingy?

**Comment by johnfactotum** [comment]
I think this a GTK bug, and looks like they've already fixed this: https://gitlab.gnome.org/GNOME/gtk/merge_requests/941
