### ISSUE TITLE
Why is org.freedesktop.Flatpak needed?

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.johnfactotum.Foliate#28]
It was added years ago without any explanation in the commit messsage https://github.com/flathub/com.github.johnfactotum.Foliate/commit/c2ea899ecf9971a25bcc73c5382763a0080dee99

Why is it required?

**Comment by johnfactotum** [comment]
See https://github.com/johnfactotum/foliate/wiki#why-does-the-flatpak-require-sandbox-escape

**Comment by bbhtt** [comment]
Can these dictionaries be included in the flatpak?

**Comment by bbhtt** [comment]
> That way it would only need read-only access to the directories that contain the dictionary data. 

That'd be nice, thanks

**Comment by johnfactotum** [comment]
v3.0 has been released and it doesn't require sandbox escape anymore. So I think this can be closed now.
